package webshop.rules.cep;

import rs.ac.uns.ftn.webshopservice.model.Buyer;
import rs.ac.uns.ftn.webshopservice.model.enums.BuyerCategory;
import rs.ac.uns.ftn.webshopservice.model.events.TransactionEvent;
import rs.ac.uns.ftn.webshopservice.service.MailSenderService;

global MailSenderService g_mailSenderService;

declare SuspiciousEvent
    @role(event)
    buyerId: Long
end

declare AlarmActivated
    buyerId: Long
end

rule "20 or more transaction in 1h"
    no-loop false
    when
        TransactionEvent($buyerId: buyerId)
        $numOfProducts: Number(intValue >= 2) from accumulate(
            $t: TransactionEvent(
                buyerId == $buyerId
            ) over window:time( 1m ),
            count($t)
        )
        not (SuspiciousEvent(buyerId == $buyerId))
    then
        insert(new SuspiciousEvent($buyerId));
        g_mailSenderService.sendWarningMail($buyerId, "Reason: 20 or more transaction are made within 1h.");
        System.out.println("[DROOLS-CEP] Created new suspicious event for buyer with id=" + $buyerId);
        System.out.println("\t20 or more products were bought within 1 hour: " + $numOfProducts + " products");
end
