package webshop.rules;

import rs.ac.uns.ftn.webshopservice.model.Buyer;
import rs.ac.uns.ftn.webshopservice.model.enums.BuyerCategory;
import rs.ac.uns.ftn.webshopservice.model.Product;
import rs.ac.uns.ftn.webshopservice.model.Order;

// global Order order;

rule "GOLD buyers have 5% discount on all articles"
    no-loop true
    when
        $order: Order()
        $buyer: Buyer()
    then
        modify($order) {
            setPrice(5554.0);
        }
        System.out.println("Aktiviralo se pravilo yyeyeyeyeyeye");
end
